services:
  - type: web
    name: arabic-exam-platform
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: arabic_exam_db
          property: connectionString
      - key: PGHOST
        fromDatabase:
          name: arabic_exam_db
          property: host
      - key: PGPORT
        fromDatabase:
          name: arabic_exam_db
          property: port
      - key: PGUSER
        fromDatabase:
          name: arabic_exam_db
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: arabic_exam_db
          property: password
      - key: PGDATABASE
        fromDatabase:
          name: arabic_exam_db
          property: database

databases:
  - name: arabic_exam_db
    plan: free
    databaseName: arabic_exam_platform
    user: arabic_exam_user